[package]
name = "bloom"
version = "0.1.0"
authors = ["maralla <maralla.ai@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["bloom filter"]
repository = "https://github.com/maralla/bloom.rs"
description = "Simple bloom filter in Rust"
